### ISSUE TITLE
shc_e2p_editor.jar /gen is creating incompatible methods

### ISSUE THREAD

**Issue by wurststulle** [breaker27/smarthomatic#118] opened 2015-01-02 11:38 UTC
e.g. for the env_sensor:

```c
In file included from shc_envsensor.c:35:0:
../src_common/e2p_envsensor.h: In function ‘e2p_envsensor_get_analoginputtriggerhysteresis’:
../src_common/e2p_envsensor.h:587:3: error: too many arguments to function ‘eeprom_read_UIntValue16’
In file included from ../src_common/e2p_hardware.h:27:0,
                 from ../src_common/util_hw.h:30,
                 from ../src_common/util.h:20,
                 from ../src_common/packet_header.h:28,
                 from ../src_common/msggrp_generic.h:27,
                 from shc_envsensor.c:28:
../src_common/e2p_access.h:51:24: note: declared here

```

and many many more :(

**Comment by breaker27** [comment] 2015-01-03 16:43
I don't get such error messages. Just generated the header files once more and compilation works without problems. Can you paste the generated function call and function signature here?
Are you sure you have the current develop version?

**Comment by breaker27** [comment] 2015-01-04 13:38
I made additional changes to the e2p layout file (xml) and the generator works as desired. Closing this issue because I don't have enought information to reproduce such an error.

**Closed by breaker27** 2015-01-04 13:38 UTC
Labels: Bug, E2P Editor, Implementing
